- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Actualizar los repositorios de apt
      apt:
        update_cache: yes
      changed_when: false

  tasks:
#    - include_tasks: tasks/factos.yml
    - include_tasks: tasks/cron_job_ansible_pull.yml
    - include_tasks: tasks/paquetes_apt.yml
    - include_tasks: tasks/anaconda.yml
    - include_tasks: tasks/rustup_root.yml
    - include_tasks: tasks/rustup_mcasl.yml
    - include_tasks: tasks/paquetes_cargo.yml
    - include_tasks: tasks/tailscale.yml
#    - include_tasks: tasks/email_final.yml
    
    


