
- name: Add ansible ppa repository
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible

- name: Ejecutar apt --fix-broken como precaución
  package:
    state: fixed
    
- name: Instalar paquetes varios
  package:
    update_cache: yes
    state: latest
    name:
      - make
      - build-essential
      - pkg-config
      - libssl-dev
      - curl
      - htop
      - mc
      - tmux
      - wireguard
      - wakeonlan
      - virtualbox
      - parallel
      - net-tools
      - nmap
      - openjdk-17-jdk
      - ansible
      - ethtool
      - sshpass
      - zsh
      - ant
      - fzf
      
