- name: Instalar paquetes varios
  package:
    name:
      - make
      - build-essential
      - sshpass
      - pkg-config
      - libssl-dev
      - curl
      - htop
      - mc
      - tmux
      - wireguard
      - wakeonlan
      - parallel
      - ethtool
      - zsh
      
