- name: Check if cargo is installed
  become_user: "mcasl"
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  failed_when: false

- name: Download rust
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: Install rust/cargo for mcasl
  when: cargo_exists is failed
  become: true
  become_user: "mcasl"
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: Add cargo in .zshrc for mcasl
  lineinfile:
    path: /home/mcasl/.zshrc
    line: "[ -f ~/.cargo/env ] && source $HOME/.cargo/env"
    create: yes
    owner: mcasl
    group: mcasl
    
- name: Add cargo in .bashrc for mcasl
  lineinfile:
    path: /home/mcasl/.bashrc
    line: "[ -f ~/.cargo/env ] && source $HOME/.cargo/env"
    create: yes
    owner: mcasl
    group: mcasl
    
- name: Instalar community.general porque es necesario para ejecutar tareas de cargo como la instalación de paquetes
  shell: ansible-galaxy collection install community.general
